### ISSUE TITLE
preproc does not report errors for missing files.

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeemerald#1250]
If preproc finds an include for an asm file that does not exist, it will silently proceed without building the asm file. If the object file for the asm file does not exist, then the build will report a missing rule error (`No rule to make target 'build/emerald/data/foo.o', needed by 'pokeemerald.elf'. Stop.`). If the object file for the asm file does exist (from a previous build), the build will continue on and use the previous object, which could lead to even more confusion. For what it's worth, a similar issue was found in pokecrystal and the fix is linked [here](https://github.com/pret/pokecrystal/commit/ea8aaeb8e3a85fa2303fe52493d840de9222f3a2).

**Comment by luckytyphlosion** [comment]
Some additional comments I forgot to add: to reproduce this, simply add the following line at the end of `data/event_scripts.`:
```
	.include "data/nonexistent.inc"
```

**Comment by GriffinRichards** [comment]
<https://github.com/pret/pokeemerald/pull/1252>
