### ISSUE TITLE
AI_PreferStrongestMove is mislabelled.

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeemerald#1272]
What it is actually intended to do is encourage moves that do no damage:
`AI_PreferStrongestMove`: https://github.com/pret/pokeemerald/blob/6dea337/src/battle_ai_script_commands.c#L1175
`get_how_powerful_move_is`: https://github.com/pret/pokeemerald/blob/6dea337/data/battle_ai_scripts.s#L2856

**Comment by GriffinRichards** [comment]
64d06f4c8fe9710863a370911cc4dd3405992d31
