### ISSUE TITLE
is8BPP in sub_8199D3C is actually isAffine

### ISSUE THREAD

**Issue by luckytyphlosion** [pret/pokeemerald#1279]
Affine tilemaps are 8 bit, while 4bpp and 8bpp are 16bit. In the function, we see that if `is8BPP` is true, then the game does an 8 bit copy, otherwise it does a 16bit copy. Thus, it makes sense that `is8BPP` is actually `isAffine`.

**Comment by GriffinRichards** [comment]
https://github.com/pret/pokeemerald/pull/1542
