### ISSUE TITLE
Is there any way to make gMapGroups not constant?

### ISSUE THREAD

**Issue by quinquice** [pret/pokeemerald#1422]
`gMapGroups` seems to be defined in `groups.inc` when it is generated, and declared externally inside `overworld.c`. I would like to be able to modify `gMapGroups` at runtime (specifically, to change the connections of maps dynamically), but nothing I do seems to work. Is it an inherent restriction of `gMapGroups` to be constant, or is this something I could work around somehow?

**Comment by Kurausukun** [comment]
These are questions to ask in #gen-3-help in the discord, not in GitHub issues.
