### ISSUE TITLE
gbafix

### ISSUE THREAD

**Issue by DarkBlade307** [pret/pokeemerald#1561]
whenever i make a change to a file, i get a line from gbafix 

example:
"tools/gbagfx/gbagfx.exe graphics/title_screen/pokemon_logo.pal graphics/title_screen/pokemon_logo.gbapal -num_colors 224"

i dont know what this means, but i never see any of my changes in the finished product. could someone please tell me how you edit the pallette files in the decompiled version properly?  in case im doing this wrong

**Comment by GriffinRichards** [comment]
Sounds like this question was addressed on Discord. If you have follow-up questions please continue there.
