### ISSUE TITLE
No LICENSE/COPYING file.

### ISSUE THREAD

**Issue by FieryMewtwo** [pret/pokeemerald#1569]
This means that no one has any rights to pokeemerald, including modifying it, playing it, or even cloning it. We could even write a license from scratch that Nintendo wouldn't be able to yell at us about.

**Comment by aaaaaa123456789** [comment]
There's no license file because, indeed, we don't have a license to the code. The code is copyrighted by Game Freak.

**Comment by FieryMewtwo** [comment]
ah. okay, I figured since this was a decomp, you guys had some rights to the code you decomped.
