### ISSUE TITLE
PNG.h missing on Apple Silicon M1 (Installed everything under Rosetta)

### ISSUE THREAD

**Issue by Manurocker95** [pret/pokeemerald#1592]
Well, I installed devkitpro and stuff under rosetta and AGBCC didn't show any issue when compiling but when compiling pokeemerald, it says png.h is missing and I guess other tools. There was other user with the same issue but never got an answer, any idea?

![image](https://user-images.githubusercontent.com/17181899/148460713-df9cd97c-b2f4-4691-a0cd-d0f427792683.png)

**Comment by GriffinRichards** [comment]
Have you installed `libpng`, per [pokeemerald's installation instructions](https://github.com/pret/pokeemerald/blob/master/INSTALL.md#macos)?

**Comment by Manurocker95** [comment]
> Have you installed `libpng`, per [pokeemerald's installation instructions](https://github.com/pret/pokeemerald/blob/master/INSTALL.md#macos)?

Yep

**Comment by GriffinRichards** [comment]
Then evidently it's not installed correctly. `png.h` is a header file belonging to `libpng`. I haven't tried the installation process on M1 as I don't have access to one, so I can't tell you if there are any additional steps you'd need to take to properly install it in that environment.

**Comment by Manurocker95** [comment]
> Then evidently it's not installed correctly. `png.h` is a header file belonging to `libpng`. I haven't tried the installation process on M1 as I don't have access to one, so I can't tell you if there are any additional steps you'd need to take to properly install it in that environment.

I tested installing libpng under rosetta, which you can clearly see it's installed:

![image](https://user-images.githubusercontent.com/17181899/148517513-4cc18f57-39b7-4807-98ec-b8aed81b1173.png)

And natively and it's kinda weird everybody with an M1 have the same exact issue (And that's why I open this issue)

**Comment by Manurocker95** [comment]
Btw, the file is is there 
![image](https://user-images.githubusercontent.com/17181899/148519247-61c04d8c-6f44-4155-b5d7-b9560736b648.png)

**Comment by Manurocker95** [comment]
OMFG, there was a discord thread. Reinstalling pnglib under rosetta explicitely over the usr/local instead of regular path worked!!!

![image](https://user-images.githubusercontent.com/17181899/148522148-4d7c9292-b264-47b1-8ef7-38c2592367b7.png)

**Comment by Manurocker95** [comment]
Until M1 native support ever arrives, the installing solution for mac should be added to the installing readme. We can close this already!

**Comment by connor-jensen** [comment]
per someone in the discord, all I had to do was run 'brew install pkg-config' and it worked
