### ISSUE TITLE
Help with compilation issues

### ISSUE THREAD

**Issue by VixtoryHax** [pret/pokeemerald#1745]
I have completed the setup for pokeemerald and agbcc, but whatever I do, I can't get past this error:
![Screenshot_3](https://user-images.githubusercontent.com/103066143/185610488-d0c6d4bc-7999-41de-8000-3201a490bc47.png)
Is there anything I need to edit?

**Comment by mrgriffin** [comment]
What changes have you made to the project? It looks like you've defined some (non-`const`) global variables that have exceeded the size of the GBA's RAM.

**Comment by VixtoryHax** [comment]
Oh I haven't touched anything at all just gone through the tutorial

**Comment by GriffinRichards** [comment]
Fixed here:
8a8ba92f21f6e6238d551dd656c6c7e5027d8ff5

It seems like some versions of ld duplicate `COMMON` with these wildcards, presumably because of the wacky way we handle that section. Hopefully the wildcards can be reintroduced at some point.
