### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by Stoutscientist** [pret/pokeemerald#1895]
If I don't actually own the game and compile this myself is playing it technically legal?

**Comment by Jaizu** [comment]
Not really no, but don't tell anyone.

**Comment by Stoutscientist** [comment]
:facepalm:

**Comment by Stoutscientist** [comment]
they really need to fix the copyright law for 20 year old games they don't sell anymore..

**Comment by PacFire** [comment]
Gee, I wonder if old games are still manufactured to this day?
