### ISSUE TITLE
I built the rom, but it just sounds off

### ISSUE THREAD

**Issue by KeeveeKoomoo** [pret/pokeemerald#1897]
The instruments seem to be a bit clipped or delayed in some cases, and I haven't even gotten past the intro sequence, and it just sounds off.

Here is what it should sound like:
https://www.youtube.com/watch?v=tnvwWrt7Rw0&ab_channel=fredfredfred

and in the file attached, is what my build sounds like.

In particular, the drums that play when torchic gets back up after falling over, and some of the trumpets near when rayquaza makes an appearance seem to just sound wrong, and also the whole thing sounds like there is less reverb put on it. I do not have this issue with roms downloaded from off the internet, so I know it isn't an emulator problem.

If anybody could help me understand what I'm doing wrong then that would be great, I haven't made any changes to the source code, this was supposed to be a simple compiling test to see if I could get it working

(the video was too big, I will compress and try again)

**Comment by KeeveeKoomoo** [comment]
https://github.com/pret/pokeemerald/assets/87249339/9021c6b2-2d34-42e0-8837-03d19bed6d5b

I've compressed it, however that doesn't appear to have affected the audio quality of the video, so you should still be able to hear the difference that I am talking about

**Comment by GriffinRichards** [comment]
This repo builds an identical copy of the original game. If something seems off to you it would be your emulator, speakers, etc., or something that you've changed, not an issue with this repo. If you need help with changes you've made there's a Discord link in the readme where you can ask questions.

**Comment by KeeveeKoomoo** [comment]
> This repo builds an identical copy of the original game. If something seems off to you it would be your emulator, speakers, etc., or something that you've changed, not an issue with this repo. If you need help with changes you've made there's a Discord link in the readme where you can ask questions.

but that's the thing, roms that I found online DO sound correct, why would that be a problem with the emulator, if other roms work but THIS rom doesn't work

**Comment by Kurausukun** [comment]
> 

Please join the discord and give more details as to what actually happened, as what you're describing is impossible. The repo by itself builds a ROM identical to one you would find online. Somewhere along the lines, something must have been edited. It would also help if you gave recordings of what sounded off about your ROM.

**Comment by GriffinRichards** [comment]
> if other roms work but THIS rom doesn't work THIS rom doesn't work

I can't verify anything about ROMs you've found online, except to say that you can check their authenticity by comparing their SHA-1 hash value to the one listed here
<https://raw.githubusercontent.com/pret/pokeemerald/master/rom.sha1>

You can also do this for the ROM produced by this repo by running `make compare`. If you run that and see the following output:
```
pokeemerald.gba: FAILED
shasum: WARNING: 1 computed checksum did NOT match
```
then either you've made changes to your project before building, or you've done something incorrectly in the course of following <https://github.com/pret/pokeemerald/blob/master/INSTALL.md>. This project (without changes and when built correctly) produces a ROM identical to the original game, so there will never be a difference between it and an authentic, original ROM.

**Comment by tustin2121** [comment]
For the sake of posterity (hello, future googlers), this was a problem with mGBA's experimental "XQ GBA Audio" enhancement feature. Turning it off (under Tools -> Settings -> Enhancements) solved OP's problem.
