### ISSUE TITLE
Build.sh make not found

### ISSUE THREAD

**Issue by DustinJoosen** [pret/pokeemerald#1913]
I am currently installing pokeemerald, while following the steps in that repository. But when attempting to run the command ```./build.sh```, in the agbcc folder it gives the error that make is not found:

```./build.sh: 14: make: not found```

Is this a common problem? 

Sudo doesn't help either. I've restarted my laptop and reinstalled the repositories. I am on windows 10 and I use a Debian console.

**Comment by LOuroboros** [comment]
"make: not found" implies that you don't have GNU Make installed, or that your environment can't find your installation of it.

What happens if you do `sudo apt install make`?

**Comment by DustinJoosen** [comment]
That worked! Thank you for the quick reaction.
I never set the environment up on my old laptop, so I missed a few things on my new laptop I see.
