### ISSUE TITLE
jsonproc improperly handles certain characters

### ISSUE THREAD

**Issue by GriffinRichards** [pret/pokeemerald#1963]
`cleanString` has special handling for `é`: https://github.com/pret/pokeemerald/blob/116364334d74242042d3ea81c6cc029d463748b7/tools/jsonproc/jsonproc.cpp#L108
but will fail to process some other reasonable characters. See https://github.com/huderlem/porymap/issues/557 for an example.

**Comment by ExcmoJack** [comment]
I would like to add that if it's possible, the right substitution should be the character without the variation, for instance: `á` for `a`.
