### ISSUE TITLE
Error on building agbcc ([Makefile:81: expr.o] Error 1)

### ISSUE THREAD

**Issue by TheDarkSword** [pret/pokeemerald#1992]
Hello, I'm on Arch Linux (EndeavourOS distro). I installed with pacman all dependencies listed in the INSTALL.md but when i try to build agbcc it fail with:
make: *** [Makefile:81: expr.o] Error 1
make: exit from directory «/home/***/pokemon-emerald/agbcc/gcc»

Here full log file: https://pastebin.com/iWbB2jU0

**Comment by PikalaxALT** [comment]
[Known issue](https://github.com/pret/agbcc/issues/68).

**Comment by TheDarkSword** [comment]
The issue is on MacOS but i'm using Arch. My gcc version is "gcc (GCC) 14.1.1 20240507".
I tried the "fix" explained in the issue but it's not working for me

**Comment by PikalaxALT** [comment]
Still, this is an issue with agbcc, not pokeemerald.
