### ISSUE TITLE
Whenever I try to make my ROM hack, it is just normal Emerald

### ISSUE THREAD

**Issue by DrPineapple416** [pret/pokeemerald#2002]
For some reason whenever I try to use make (specifically make -j4), it looks normal on my output but I just end up with a normal Emerald Version.
![image](https://github.com/pret/pokeemerald/assets/172821061/379fe452-1a27-41ff-b9b3-21be9a7cf37a)

**Comment by DrPineapple416** [comment]
Just checked right now, and the starters are different (I changed them) but not the map (Also changed that)

**Comment by LOuroboros** [comment]
Chances are that you might have some errors to fix and the tools are not making a good job at pointing that out.

Try a `make clean` followed by a `make` *(not `make -j4`, just `make`)*. If you get any compilation errors, you'll have to fix those.

**Comment by SBird1337** [comment]
Parts of the map are saved in the savefile. If you changed that you need to make sure to at least switch the map.

This is not directly related to an issue with the project. If you have further questions feel free to join the pret Discord.
