### ISSUE TITLE
Cycling Road North/South entrances mislabeled

### ISSUE THREAD

**Issue by Scyrous** [pret/pokeemerald#2008]
The north and south entrances of the Cycling Road (and all of their contents) are mislabeled in pret/pokeemerald. According to Bulbapedia, other sources, and general common sense, the entrance closest to Mauville City is the north entrance, and the one closest to Slateport City is the south entrance. However, the current labels are reversed.

As an example, I made this quick edit using Porymap. I moved this NPC a few tiles to the left in the **northern** house.

![image](https://github.com/pret/pokeemerald/assets/74797764/85798996-1d81-44d3-94ce-96a960626ba8)

As you can see, the change appears in the **southern** house. Feel free to make your own changes and test for yourself to verify this mislabeling.

![South](https://github.com/pret/pokeemerald/assets/74797764/29103301-d40f-46dd-86ae-1e0d675dbe12)

As far as I can tell, this applies to all of the contents and labels in the folders `Route110_SeasideCyclingRoadNorthEntrance` and `Route110_SeasideCyclingRoadSouthEntrance`.

**Comment by GriffinRichards** [comment]
Thanks! Fixed: 04197b49126604a310fae1d314709334f6d2460d
