### ISSUE TITLE
baserom.gba

### ISSUE THREAD

**Issue by nopy4869** [pret/pokeemerald#4]
What is the baserom.gba file and how do I generate it?

**Comment by YamaArashi** [comment]
This repository does not use such a file. You may be thinking of the pokeruby reposition. In that case, it's the rom file for the game.

**Comment by nopy4869** [comment]
I actually meant to post this in the Pokeruby repo. Is there a specific hash that the baserom has?

**Comment by YamaArashi** [comment]
Yes. It is in the Readme of the pokeruby repository. It is the no-intro sha1 hash

**Comment by nopy4869** [comment]
Ok thank you, you've been a huge help.
