### ISSUE TITLE
BG_CTRL_ATTR enum is mislabeled

### ISSUE THREAD

**Issue by huderlem** [pret/pokeemerald#411]
In `include/bg.h`
```
enum
{
    BG_CTRL_ATTR_VISIBLE = 1,
    BG_CTRL_ATTR_CHARBASEINDEX = 2,
    BG_CTRL_ATTR_MAPBASEINDEX = 3,
    BG_CTRL_ATTR_SCREENSIZE = 4,
    BG_CTRL_ATTR_PALETTEMODE = 5,
    BG_CTRL_ATTR_PRIORITY = 6,
    BG_CTRL_ATTR_MOSAIC = 7,
    BG_CTRL_ATTR_WRAPAROUND = 8,
};
```

These are mislabeled, which can be seen by examining `SetBgAttribute()` in `src/bg.c`.  They might simply be off-by-one.

**Comment by DizzyEggg** [comment]
The attributes for GetBgAttribute and GetBgControlAttribute are different. I think we should make two separate enums for them.
