### ISSUE TITLE
Resolve Oam matrixNum vs. flip

### ISSUE THREAD

**Issue by huderlem** [pret/pokeemerald#498]
In `OamData`, the GBA re-purposes two bits in the `matrixNum` field (rot/scale selection).

```
u32 matrixNum:5; // bits 3/4 are h-flip/v-flip if not in affine mode
```

This makes some code very confusing to read because you have to "just know" this fact.  In this example, the sprite's `hFlip` is getting set to true, but it looks like it's manipulating the rot-scale matrix number.
```
if (GetBattlerSide(sprite->data[7]) == B_SIDE_OPPONENT)
        sprite->oam.matrixNum = 8;
```

We should either create a macro or see if a union can be used in the `OamData` struct.

**Comment by DizzyEggg** [comment]
Personally, I'd prefer a macro.

**Comment by PikalaxALT** [comment]
Propose something like this in `include/gba/types.h`:
```c
#define ST_OAM_MNUM_HFLIP     (1 << 3)
#define ST_OAM_MNUM_VFLIP     (1 << 4)
#define ST_OAM_MNUM_FLIP_MASK 0x18
```

**Comment by PikalaxALT** [comment]
Resolved
