### ISSUE TITLE
Calcrom does not read sizes that span multiple lines or have extra text after ".text"

### ISSUE THREAD

**Issue by Diegoisawesome** [pret/pokeemerald#520]
We specifically run into this issue with ` .text.after.match.call`, which doesn't get regex matched and therefore doesn't get added into the size calculations.

**Comment by DizzyEggg** [comment]
We kinda did a work-around and simply got rid of the troubling part. Can this be closed now?

**Comment by Diegoisawesome** [comment]
I guess so, this was a very specific problem.
