### ISSUE TITLE
Seperate out GFlib.

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokeemerald#528]
I previously noted this, but I believe I figured out the behavior of file link order. It is related to file creation timestamp (not file update). However, in order for this to make sense, a specific section of files near the beginning need to be their own linked library (ie GfLib), which are also self-ordered by file creation timestamp.

![image](https://user-images.githubusercontent.com/11638236/51937248-23ad9f80-23d8-11e9-8f2a-c6de915df1bc.png)

rtc.c is not part of Gflib. If it were, union room in emerald would be, which references tasks.

For ruby, 
```
src/sprite.o(.text);
src/text.o(.text);
src/string_util.o(.text);
```
are Gflib.

Fire Red asserts also point to malloc being gflib, hence this theory. Once you consider this area as a compiled linked library, file creation timestamps make sense. I think we should move them to src/gflib/ at the very least, ideally we need to compile gflib.a before linking to the ROM.

**Comment by PikalaxALT** [comment]
Resolved in #802
