### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by jirachiwishmaker** [pret/pokeemerald#6]
Hi, @YamaArashi. Would you mind telling me the assembly code controlling the easy-chat words used in the pre-battle speech, the win speech and the loss speech of the trainers of Battle Frontier? Thanks in advance.

**Comment by YamaArashi** [comment]
I don't quite understand which code you're referring to. Are you referring to the battle frontier code that reads the easy chat words from the battle frontier trainer structs or the code that translates easy chat word ID numbers into strings?

**Comment by jirachiwishmaker** [comment]
Actually it is the latter. I personally would like to give Battle Frontier opponents actual text strings instead of easy-chat system . Anyone decapitalizing the game is going to be making the easy chat system a wreck anyway. Could their data be restructured so that the easy-chat choices are pointers to text strings instead?

**Comment by YamaArashi** [comment]
I believe the address of the function that does this is 81638AC. It would be possible to change the code to allow what you are describing, but for the moment you would need to use traditional ROM hacking methods such as repointing.

**Comment by jirachiwishmaker** [comment]
Oh, I see. Is the code, 08005ED8 I should change at 0x1638C6 or not? But I don't know what is the offset I should put it at here.

**Comment by jirachiwishmaker** [comment]
@YamaArashi, could you help me only for this hacking, please? I really need it so much.

**Comment by YamaArashi** [comment]
Sorry, but I'm not that familiar with hacking Emerald. I am currently working on Ruby more. https://github.com/pret/pokeruby Soon it will be easy to make hacks like this for Ruby, but this disassembly needs quite a bit of work before the same could be done for Emerald.

**Comment by jirachiwishmaker** [comment]
Anyway, thank you for providing the function offset to me.
