### ISSUE TITLE
Disambiguate macro names for Speed and Sp. Def stats

### ISSUE THREAD

**Issue by sphericalice** [pret/pokeemerald#66]
Currently, MON_DATA_SPD is an ambiguous macro name as outside of the context of MON_DATA_SPDEF it is unclear if it refers to the Speed stat or the Special Defense stat.

Either settle on a consistent length and use SPE for Speed:

- MON_DATA_SPA
- MON_DATA_SPD
- MON_DATA_SPE

Or spell out SPEED in full:

- MON_DATA_SPATK
- MON_DATA_SPDEF
- MON_DATA_SPEED
Note that SPEED is five characters, which is the same as SPATK and SPDEF which is currently in use.

The former is arguably easier, but the latter is completely unambiguous while being slightly more verbose.

**Comment by Diegoisawesome** [comment]
Agreed, and I vote for the second option.

**Comment by camthesaxman** [comment]
I already fixed this. 1bb931245b5030746b7150e3965520954d0068a7
