### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by DizzyEggg** [pret/pokeemerald#7]
Win7

scaninc.exe - application error
Application can't be properly activated (0xc000007b)

**Comment by YamaArashi** [comment]
Did you compile scaninc.exe yourself or did you use the precompiled copy from https://github.com/YamaArashi/pokeruby-tools?

**Comment by DizzyEggg** [comment]
I used the one at rubytools

**Comment by yenatch** [comment]
`chmod +x tools/*/*.exe tools/*/*/*.exe`

**Comment by YamaArashi** [comment]
I updated the repo. https://github.com/YamaArashi/pokeruby-tools/commit/e4160a630f3c5f408c6842de41f1569c2d0ea3f2

**Comment by DizzyEggg** [comment]
Still get the same error

**Comment by YamaArashi** [comment]
did you install the the runtime DLL mentioned in the README? https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by DizzyEggg** [comment]
I needed to download correct runtime DLL(in my case it was x86) as well as the MSYS that comes with the devkitpro.
