### ISSUE TITLE
Build process ignores the $CC and $CXX environment variables

### ISSUE THREAD

**Issue by aaaaaa123456789** [pret/pokeemerald#742]
I'm pretty sure this is an issue that spans all of pret's makefiles and build scripts, but here's where I found it, so here's where I'm opening it.

The values of the `$CC` and `$CXX` environment variables is completely ignored; the names of `gcc` and `g++` are hardcoded. In systems like mine, with several versions of those tools, this causes the wrong tool to be invoked, leading to build failures.

**Comment by mid-kid** [comment]
Note that `$CC` and `$CXX` are supposed to point to the system's host compiler, not to a cross-compiler. As such, it makes sense to ignore them in that context. I assume you're talking about the tools makefiles, however?

**Comment by aaaaaa123456789** [comment]
I'm talking about stuff built with the host compiler, yes. I'm not sure if that's just the tools' makefiles or if the main makefile invokes it too.

**Comment by PikalaxALT** [comment]
Afaik it's just the tools. Main makefile doesn't care except in the devkitARM-free repositories which define `CPP := $(CC) -E`.

**Comment by PikalaxALT** [comment]
On testing, this claim does not hold water.  (Ignore the error, I don't have libpng for the mingw32 target in this environment.)

```
pokeemerald$ make tools CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
i686-w64-mingw32-g++ -Wall -std=c++11 -O2 json11.cpp mapjson.cpp -o mapjson
i686-w64-mingw32-gcc -Wall -Wextra -Wno-switch -Werror -std=c11 -O2 main.c extended.c -o aif2pcm  -lm
i686-w64-mingw32-g++ -Wall -std=c++11 -O2 -I . jsonproc.cpp -o jsonproc
i686-w64-mingw32-g++ -std=c++11 -O2 -Wall -Wno-switch -Werror main.cpp sym_file.cpp elf.cpp -o ramscrgen
i686-w64-mingw32-g++ -Wall -Werror -std=c++11 -O2 scaninc.cpp c_file.cpp asm_file.cpp source_file.cpp -o scaninc
i686-w64-mingw32-gcc -Wall -Wextra -Werror -std=c11 -O2 bin2c.c -o bin2c
i686-w64-mingw32-gcc -Wall -Wextra -Werror -std=c11 -O2 -DPNG_SKIP_SETJMP_CHECK main.c convert_png.c util.c font.c -o rsfont  -lpng -lz
convert_png.c:5:10: fatal error: png.h: No such file or directory
 #include <png.h>
          ^~~~~~~
compilation terminated.
Makefile:12: recipe for target 'rsfont' failed
make[1]: *** [rsfont] Error 1
Makefile:138: recipe for target 'tools/rsfont' failed
make: *** [tools/rsfont] Error 2
```

**Comment by PikalaxALT** [comment]
Edit: The issue is in the `build_tools.sh` script, which will soon be deprecated.

**Comment by aaaaaa123456789** [comment]
Environment variables ≠ make variables.

Make variables: `make FOO=BAR`
Environment variables: `FOO=BAR make`

Environment variables can also be predefined (e.g., in the .bashrc file); the above example is equivalent to:
```bash
export FOO=BAR
make
```

**Comment by PikalaxALT** [comment]
I see what you're saying.  This is intentional to avoid the ARM compilers being passed to compile the tools.

**Comment by aaaaaa123456789** [comment]
The ARM compilers should never be passed through those variables; those variables are intended for the _host_ compilers. Anyone who has ARM compilers there (without having an ARM CPU) has a misconfiguration in their system.

**Comment by mid-kid** [comment]
The ARM compilers should only be set in the root makefile, but never passed down through the environment to the tools.
