### ISSUE TITLE
Hard-to-reproduce tilemap glitch

### ISSUE THREAD

**Issue by PikalaxALT** [pret/pokeemerald#747]
When compiling Emerald with GCC-8.3.0 or GCC-9.1.0, a weird graphical glitch sometimes occurs after a BG redraw. This glitch is difficult to reproduce but has been observed on both emulator and console.

Example:
![Screenshot of messed-up bg tilemap when emerging from Meteor Falls (Route 115 side)](https://cdn.discordapp.com/attachments/442465020291317760/601830555599896576/unknown.png)

**Comment by PikalaxALT** [comment]
Glitch occurs when REG_BG((x))CNT is not properly set for display.  In the screenshot above, REG_BG2CNT = 0000 when it should be 421C (priority 2, mosaic, screen base 28)

**Comment by PikalaxALT** [comment]
Glitch is likely the result of the semaphore `sGpuRegBufferLocked` being the wrong type (`bool8` instead of `vu8`).

**Comment by atasro2** [comment]
why hasn't this been closed yet?
