### ISSUE TITLE
How should I solve this problem?

### ISSUE THREAD

**Issue by WeiXiaoBlueRabbit** [pret/pokeemerald#754]
This problem occurs during compilation:
devkitARM\bin\arm-none-eabi-ld.exe: cannot find sound/songs/se: No such file or directory
make: *** [pokeemerald.elf] error 1

what should i do?

**Comment by PikalaxALT** [comment]
Hi, sorry for the delay in responding to this issue. Have you figured it out on your own?  If not, please provide additional details:
- What terminal (cygwin, msys2)?
- If you run `make clean && make compare`, do you still get the error?
- If the answer to the above is "yes", please share the last 10 lines of console output.

**Comment by WeiXiaoBlueRabbit** [comment]
> 
> 
> Hi, sorry for the delay in responding to this issue. Have you figured it out on your own? If not, please provide additional details:
> 
>     * What terminal (cygwin, msys2)?
> 
>     * If you run `make clean && make compare`, do you still get the error?
> 
>     * If the answer to the above is "yes", please share the last 10 lines of console output.

**Comment by WeiXiaoBlueRabbit** [comment]
> 
> 
> Hi, sorry for the delay in responding to this issue. Have you figured it out on your own? If not, please provide additional details:
> 
>     * What terminal (cygwin, msys2)?
> 
>     * If you run `make clean && make compare`, do you still get the error?
> 
>     * If the answer to the above is "yes", please share the last 10 lines of console output.

Yes, I have solved it. Thank you for your reply!
