### ISSUE TITLE
Code Build failed

### ISSUE THREAD

**Issue by Dokman** [pret/pokeemerald#870]
include <png.h> does not fount
what i can do i setted up properlty the DevKitPro in ubuntu

PS: after do sudo apt-getinstall-libpng-dev it was fixed but now i am obtaining this error

![image](https://user-images.githubusercontent.com/2290904/68084015-40c44280-fe30-11e9-80df-723c1dd3848d.png)

**Comment by PikalaxALT** [comment]
Please visit the discord for assistance.
