### ISSUE TITLE
Tileset animations

### ISSUE THREAD

**Issue by maierfelix** [pret/pokeemerald#90]
Can someone elaborate on
https://github.com/pret/pokeemerald/blob/master/src/tileset_anims.c#L752

How does the animation patch the correct tile inside the tileset? Can we calculate an actual tileset tile index (like [here](https://image.prntscr.com/image/dIonsO_IRV2SgnqGfF3bPw.png)) out of the ``0x3F80``?

**Comment by ProjectRevoTPP** [comment]
Why was this closed?

**Comment by maierfelix** [comment]
It just happens to be equal to a tileset's tile index
